/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica6_2;

import java.awt.AlphaComposite;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Composite;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GraphicsEnvironment;
import java.awt.Paint;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Shape;
import java.awt.Stroke;
import java.awt.geom.Line2D;
import java.awt.geom.Point2D;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 *
 * @author Mario
 */
public class VentanaPrincipal extends javax.swing.JFrame {

   
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        GraphicsEnvironment ge;
        ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String []fuentesSistema = ge.getAvailableFontFamilyNames();
        combo_fuente.setModel(new javax.swing.DefaultComboBoxModel<>(fuentesSistema));
        combo_fuente.setSelectedItem("Arial");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cb_editar = new javax.swing.JCheckBox();
        cb_relleno = new javax.swing.JCheckBox();
        combo_fuente = new javax.swing.JComboBox<>();
        cb_ventana = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        lienzo1 = new practica6_2.Lienzo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        cb_editar.setText("Editar");
        cb_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_editarActionPerformed(evt);
            }
        });
        jPanel1.add(cb_editar);

        cb_relleno.setText("Relleno");
        cb_relleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_rellenoActionPerformed(evt);
            }
        });
        jPanel1.add(cb_relleno);

        combo_fuente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_fuente.setToolTipText("");
        combo_fuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_fuenteActionPerformed(evt);
            }
        });
        jPanel1.add(combo_fuente);

        cb_ventana.setText("Efecto ventana");
        cb_ventana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ventanaActionPerformed(evt);
            }
        });
        jPanel1.add(cb_ventana);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_editarActionPerformed
        lienzo1.setEditar(cb_editar.isSelected());
    }//GEN-LAST:event_cb_editarActionPerformed

    private void cb_rellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_rellenoActionPerformed
        lienzo1.setRelleno(cb_relleno.isSelected());
        lienzo1.repaint();
    }//GEN-LAST:event_cb_rellenoActionPerformed

    private void combo_fuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_fuenteActionPerformed
        lienzo1.setFuente((String) combo_fuente.getSelectedItem());
        lienzo1.repaint();
    }//GEN-LAST:event_combo_fuenteActionPerformed

    private void cb_ventanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ventanaActionPerformed
        lienzo1.setVentanaClipActiva(cb_ventana.isSelected());
        lienzo1.repaint();
    }//GEN-LAST:event_cb_ventanaActionPerformed

    /**
     * @param args the command line arguments
     */
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb_editar;
    private javax.swing.JCheckBox cb_relleno;
    private javax.swing.JCheckBox cb_ventana;
    private javax.swing.JComboBox<String> combo_fuente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private practica6_2.Lienzo lienzo1;
    // End of variables declaration//GEN-END:variables
}
