/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica11;

import SM.MRC.iu.Lienzo2DImagen;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.geom.Point2D;
import java.awt.image.BufferedImage;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JToggleButton;

/**
 *
 * @author Mario
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    private VentanaPrincipal parent = null;

    public Lienzo2DImagen getLienzo() {
        return lienzo2DImagen;
    }    
    
    /**
     * Creates new form VentanaInterna
     */
    public VentanaInterna(VentanaPrincipal parent) {
        initComponents();
        this.parent = parent;
        lienzo2DImagen.setBorde(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanel = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        lienzo2DImagen = new SM.MRC.iu.Lienzo2DImagen();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nuevo Lienzo2DImagen");
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(300, 350));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(false);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panel.setBackground(new java.awt.Color(204, 204, 204));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lienzo2DImagen.setBackground(new java.awt.Color(255, 255, 255));
        lienzo2DImagen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lienzo2DImagenMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lienzo2DImagenMouseMoved(evt);
            }
        });
        lienzo2DImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lienzo2DImagenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lienzo2DImagenMouseExited(evt);
            }
        });

        javax.swing.GroupLayout lienzo2DImagenLayout = new javax.swing.GroupLayout(lienzo2DImagen);
        lienzo2DImagen.setLayout(lienzo2DImagenLayout);
        lienzo2DImagenLayout.setHorizontalGroup(
            lienzo2DImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        lienzo2DImagenLayout.setVerticalGroup(
            lienzo2DImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        panel.add(lienzo2DImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        scrollPanel.setViewportView(panel);

        getContentPane().add(scrollPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated

        parent.getGrupoBarraHerramientas().clearSelection();

        // Obtener el JToggleButton seleccionado del grupo de botones
        JToggleButton jb = new JToggleButton(); int i = 0;
        for (Enumeration<AbstractButton> h = parent.getGrupoBarraHerramientas().getElements(); h.hasMoreElements();) {
            jb = (JToggleButton) h.nextElement();
            if(i==lienzo2DImagen.getHerramienta().ordinal())
                break;
            i++;
        }
        jb.setSelected(true);

        parent.getBarraEstado().setText(jb.getName());
        
        JButton cb = new JButton(); i = 0;
        for (Enumeration<AbstractButton> h = parent.getGrupoColores().getElements(); h.hasMoreElements();) {
            cb = (JButton) h.nextElement();
            if(i==lienzo2DImagen.getColor().ordinal())
                break;
            i++;
        }
        
        parent.getComboColor().setSelectedIndex(i);
        
        parent.getSpinnerGrosor().setValue(lienzo2DImagen.getGrosor());

        parent.getBotonRelleno().setSelected(lienzo2DImagen.isRelleno());
        parent.getBotonTransparencia().setSelected(lienzo2DImagen.isTransparencia());
        parent.getBotonAlisar().setSelected(lienzo2DImagen.isAlisar());
        
    }//GEN-LAST:event_formInternalFrameActivated

    private void lienzo2DImagenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2DImagenMouseEntered
        parent.getPanelPosicion().setPreferredSize(new Dimension(190,30));
    }//GEN-LAST:event_lienzo2DImagenMouseEntered
    
    private void lienzo2DImagenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2DImagenMouseExited
        parent.getPanelPosicion().setPreferredSize(new Dimension(10,30));
        parent.getLabelPosicion().setText("");
        parent.getLabelRGB().setText("");
    }//GEN-LAST:event_lienzo2DImagenMouseExited

    private void lienzo2DImagenMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2DImagenMouseMoved
        parent.getLabelPosicion().setText("("+(int)evt.getPoint().getX()+","+(int)evt.getPoint().getY()+")");
        if (evt.getPoint().getX() > 1000 && evt.getPoint().getX() > 1000)
            parent.getPanelPosicion().setPreferredSize(new Dimension(200,30));
        BufferedImage imgSource = getLienzo().getImagen();
        if(imgSource != null)
            if( imgSource.getColorModel().getColorSpace().isCS_sRGB()){
                if((new Rectangle(0, 0, imgSource.getWidth(), imgSource.getHeight())).contains(evt.getPoint()))
                    parent.getLabelRGB().setText(
                         "R: "  + imgSource.getRaster().getSample((int)evt.getPoint().getX(), (int)evt.getPoint().getY(), 0)+
                         " G: " + imgSource.getRaster().getSample((int)evt.getPoint().getX(), (int)evt.getPoint().getY(), 1)+
                         " B: " + imgSource.getRaster().getSample((int)evt.getPoint().getX(), (int)evt.getPoint().getY(), 2)
                    ); 
                else
                    parent.getLabelRGB().setText(""); 
            }else{
                parent.getLabelRGB().setText("B: " + imgSource.getRaster().getSample((int)evt.getPoint().getX(), (int)evt.getPoint().getY(), 0));
            }
        
       
    }//GEN-LAST:event_lienzo2DImagenMouseMoved

    private void lienzo2DImagenMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2DImagenMouseDragged
        parent.getLabelPosicion().setText("("+(int)evt.getPoint().getX()+","+(int)evt.getPoint().getY()+")");
        BufferedImage imgSource = getLienzo().getImagen();
        if( imgSource.getColorModel().getColorSpace().isCS_sRGB()){
                if((new Rectangle(0, 0, imgSource.getWidth(), imgSource.getHeight())).contains(evt.getPoint()))
                    parent.getLabelRGB().setText(
                         "R: "  + imgSource.getRaster().getSample((int)evt.getPoint().getX(), (int)evt.getPoint().getY(), 0)+
                         " G: " + imgSource.getRaster().getSample((int)evt.getPoint().getX(), (int)evt.getPoint().getY(), 1)+
                         " B: " + imgSource.getRaster().getSample((int)evt.getPoint().getX(), (int)evt.getPoint().getY(), 2)
                    ); 
                else
                    parent.getLabelRGB().setText(""); 
        }
    }//GEN-LAST:event_lienzo2DImagenMouseDragged

    public void mostrarVentanaCascada(JDesktopPane escritorio){
        // Mostrar las nuevas ventanas en cascada
        if(escritorio.getComponentCount()>0){
            // Obtener la posición de la última ventana
            Point2D p_ultima_vi = escritorio.getComponents()[0].getLocation();
            Point2D cascada = new Point((int)p_ultima_vi.getX()+25, (int)p_ultima_vi.getY()+25);
            this.setLocation((Point) cascada);
        }
        escritorio.add(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SM.MRC.iu.Lienzo2DImagen lienzo2DImagen;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables
}
