/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica4;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JToggleButton;


/**
 *
 * @author Mario
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    
    
    public VentanaPrincipal() {
        initComponents();
        miInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBarraHerramientas = new javax.swing.ButtonGroup();
        dialogoAbrir = new javax.swing.JDialog();
        fileChooserAbrir = new javax.swing.JFileChooser();
        dialogoGuardar = new javax.swing.JDialog();
        fileChooserCerrar = new javax.swing.JFileChooser();
        panelInferior = new javax.swing.JPanel();
        panelInferiorCentro = new javax.swing.JPanel();
        panelColores = new javax.swing.JPanel();
        botonNegro = new javax.swing.JButton();
        botonBlanco = new javax.swing.JButton();
        botonRojo = new javax.swing.JButton();
        botonAmarillo = new javax.swing.JButton();
        botonAzul = new javax.swing.JButton();
        botonVerde = new javax.swing.JButton();
        rellenoCB = new javax.swing.JCheckBox();
        herramientaText = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        panelLienzo = new practica4.Lienzo();
        barraHerramientas = new javax.swing.JToolBar();
        botonLapiz = new javax.swing.JToggleButton();
        botonLinea = new javax.swing.JToggleButton();
        botonRectangulo = new javax.swing.JToggleButton();
        botonOvalo = new javax.swing.JToggleButton();
        menuPrincipal = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemNuevo = new javax.swing.JMenuItem();
        itemAbrir = new javax.swing.JMenuItem();
        itemGuardar = new javax.swing.JMenuItem();
        menuEdicion = new javax.swing.JMenu();
        itemVer = new javax.swing.JCheckBoxMenuItem();

        FormListener formListener = new FormListener();

        dialogoAbrir.setSize(new java.awt.Dimension(643, 419));
        dialogoAbrir.getContentPane().setLayout(new javax.swing.BoxLayout(dialogoAbrir.getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        dialogoAbrir.getContentPane().add(fileChooserAbrir);

        dialogoGuardar.setSize(new java.awt.Dimension(643, 419));
        dialogoGuardar.getContentPane().setLayout(new javax.swing.BoxLayout(dialogoGuardar.getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        dialogoGuardar.getContentPane().add(fileChooserCerrar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PaintBásico");

        panelInferior.setLayout(new java.awt.BorderLayout());

        panelInferiorCentro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelInferiorCentro.setLayout(new java.awt.BorderLayout());

        botonNegro.setBackground(new java.awt.Color(0, 0, 0));
        botonNegro.addActionListener(formListener);

        botonBlanco.setBackground(new java.awt.Color(255, 255, 255));

        botonRojo.setBackground(new java.awt.Color(255, 0, 0));

        botonAmarillo.setBackground(new java.awt.Color(255, 255, 0));

        botonAzul.setBackground(new java.awt.Color(0, 0, 255));

        botonVerde.setBackground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout panelColoresLayout = new javax.swing.GroupLayout(panelColores);
        panelColores.setLayout(panelColoresLayout);
        panelColoresLayout.setHorizontalGroup(
            panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColoresLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelColoresLayout.createSequentialGroup()
                        .addComponent(botonNegro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(botonRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(botonAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelColoresLayout.createSequentialGroup()
                        .addComponent(botonBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(botonAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(botonVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelColoresLayout.setVerticalGroup(
            panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColoresLayout.createSequentialGroup()
                .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonRojo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(botonAzul, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(botonNegro, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonAmarillo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(botonVerde, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(botonBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
        );

        panelInferiorCentro.add(panelColores, java.awt.BorderLayout.CENTER);

        rellenoCB.setText("Relleno");
        rellenoCB.addActionListener(formListener);
        panelInferiorCentro.add(rellenoCB, java.awt.BorderLayout.LINE_END);

        panelInferior.add(panelInferiorCentro, java.awt.BorderLayout.NORTH);

        herramientaText.setText("Punto");
        herramientaText.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelInferior.add(herramientaText, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(panelInferior, java.awt.BorderLayout.PAGE_END);

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelLienzo.setName("Lapiz"); // NOI18N

        javax.swing.GroupLayout panelLienzoLayout = new javax.swing.GroupLayout(panelLienzo);
        panelLienzo.setLayout(panelLienzoLayout);
        panelLienzoLayout.setHorizontalGroup(
            panelLienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 841, Short.MAX_VALUE)
        );
        panelLienzoLayout.setVerticalGroup(
            panelLienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelLienzo, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        barraHerramientas.setRollover(true);

        grupoBarraHerramientas.add(botonLapiz);
        botonLapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Lapiz.gif"))); // NOI18N
        botonLapiz.setSelected(true);
        botonLapiz.setFocusable(false);
        botonLapiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonLapiz.setName("Punto"); // NOI18N
        botonLapiz.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraHerramientas.add(botonLapiz);

        grupoBarraHerramientas.add(botonLinea);
        botonLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Linea.gif"))); // NOI18N
        botonLinea.setFocusable(false);
        botonLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonLinea.setName("Línea"); // NOI18N
        botonLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraHerramientas.add(botonLinea);

        grupoBarraHerramientas.add(botonRectangulo);
        botonRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Rectangulo.gif"))); // NOI18N
        botonRectangulo.setFocusable(false);
        botonRectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRectangulo.setName("Rectángulo"); // NOI18N
        botonRectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraHerramientas.add(botonRectangulo);

        grupoBarraHerramientas.add(botonOvalo);
        botonOvalo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Ovalo.gif"))); // NOI18N
        botonOvalo.setFocusable(false);
        botonOvalo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonOvalo.setName("Elipse"); // NOI18N
        botonOvalo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraHerramientas.add(botonOvalo);

        getContentPane().add(barraHerramientas, java.awt.BorderLayout.NORTH);

        menuArchivo.setText("Archivo");

        itemNuevo.setText("Nuevo");
        itemNuevo.addActionListener(formListener);
        menuArchivo.add(itemNuevo);

        itemAbrir.setText("Abrir");
        itemAbrir.addActionListener(formListener);
        menuArchivo.add(itemAbrir);

        itemGuardar.setText("Guardar");
        itemGuardar.addActionListener(formListener);
        menuArchivo.add(itemGuardar);

        menuPrincipal.add(menuArchivo);

        menuEdicion.setText("Edición");

        itemVer.setSelected(true);
        itemVer.setText("Ver barra de estado");
        itemVer.addItemListener(formListener);
        menuEdicion.add(itemVer);

        menuPrincipal.add(menuEdicion);

        setJMenuBar(menuPrincipal);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.ItemListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == rellenoCB) {
                VentanaPrincipal.this.rellenoCBActionPerformed(evt);
            }
            else if (evt.getSource() == itemNuevo) {
                VentanaPrincipal.this.itemNuevoActionPerformed(evt);
            }
            else if (evt.getSource() == itemAbrir) {
                VentanaPrincipal.this.itemAbrirActionPerformed(evt);
            }
            else if (evt.getSource() == itemGuardar) {
                VentanaPrincipal.this.itemGuardarActionPerformed(evt);
            }
            else if (evt.getSource() == botonNegro) {
                VentanaPrincipal.this.botonNegroActionPerformed(evt);
            }
        }

        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            if (evt.getSource() == itemVer) {
                VentanaPrincipal.this.itemVerItemStateChanged(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void itemVerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_itemVerItemStateChanged
        herramientaText.setVisible(itemVer.getState());
    }//GEN-LAST:event_itemVerItemStateChanged

    private void itemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNuevoActionPerformed
        panelLienzo.reinicia();
        grupoBarraHerramientas.clearSelection();
        botonLapiz.setSelected(true);
        rellenoCB.setSelected(false);
        panelLienzo.repaint();
    }//GEN-LAST:event_itemNuevoActionPerformed

    private void itemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAbrirActionPerformed
        dialogoAbrir.setVisible(true); 
        dialogoAbrir.setTitle("Abrir");
    }//GEN-LAST:event_itemAbrirActionPerformed

    private void itemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGuardarActionPerformed
        dialogoGuardar.setVisible(true); 
        dialogoGuardar.setTitle("Guardar");
    }//GEN-LAST:event_itemGuardarActionPerformed

    private void rellenoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rellenoCBActionPerformed
        panelLienzo.setRelleno(rellenoCB.isSelected());
    }//GEN-LAST:event_rellenoCBActionPerformed

    private void botonNegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNegroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNegroActionPerformed

    private void miInitComponents(){
        
        class ColorListener extends MouseAdapter  {
            ColorListener() {}
            public void mouseClicked(MouseEvent evt) {
                JButton botonColor = (JButton) evt.getSource();
                panelLienzo.setColor(botonColor.getBackground());
                panelLienzo.repaint();
            }
        }
        ColorListener colorListener = new ColorListener();
        botonNegro.addMouseListener(colorListener);
        botonRojo.addMouseListener(colorListener);
        botonAzul.addMouseListener(colorListener);
        botonBlanco.addMouseListener(colorListener);
        botonAmarillo.addMouseListener(colorListener);
        botonVerde.addMouseListener(colorListener);
        
        class HerramientasListener extends MouseAdapter {
            HerramientasListener(){}
            public void mouseClicked(MouseEvent evt){
                JToggleButton herramientaBoton = (JToggleButton) evt.getSource();
                panelLienzo.setHerramienta(Herramienta.valueOf(herramientaBoton.getName()));
                herramientaText.setText(herramientaBoton.getName());
            }
        }
        HerramientasListener herramientasListener = new HerramientasListener();
        botonLapiz.addMouseListener(herramientasListener);
        botonLinea.addMouseListener(herramientasListener);
        botonRectangulo.addMouseListener(herramientasListener);
        botonOvalo.addMouseListener(herramientasListener);
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraHerramientas;
    private javax.swing.JButton botonAmarillo;
    private javax.swing.JButton botonAzul;
    private javax.swing.JButton botonBlanco;
    private javax.swing.JToggleButton botonLapiz;
    private javax.swing.JToggleButton botonLinea;
    private javax.swing.JButton botonNegro;
    private javax.swing.JToggleButton botonOvalo;
    private javax.swing.JToggleButton botonRectangulo;
    private javax.swing.JButton botonRojo;
    private javax.swing.JButton botonVerde;
    private javax.swing.JDialog dialogoAbrir;
    private javax.swing.JDialog dialogoGuardar;
    private javax.swing.JFileChooser fileChooserAbrir;
    private javax.swing.JFileChooser fileChooserCerrar;
    private javax.swing.ButtonGroup grupoBarraHerramientas;
    private javax.swing.JLabel herramientaText;
    private javax.swing.JMenuItem itemAbrir;
    private javax.swing.JMenuItem itemGuardar;
    private javax.swing.JMenuItem itemNuevo;
    private javax.swing.JCheckBoxMenuItem itemVer;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuEdicion;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JPanel panelColores;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelInferiorCentro;
    private practica4.Lienzo panelLienzo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JCheckBox rellenoCB;
    // End of variables declaration//GEN-END:variables
}
