/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Practica6;

import java.awt.AlphaComposite;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Composite;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Paint;
import java.util.List;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Shape;
import java.awt.Stroke;
import java.awt.geom.CubicCurve2D;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.geom.Point2D;
import java.awt.geom.QuadCurve2D;
import java.awt.geom.Rectangle2D;
import java.awt.geom.RoundRectangle2D;
import java.util.ArrayList;

/**
 *
 * @author Mario
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private Line2D linea;
    private Rectangle rectangulo;
    private Point paux;
    List<Shape> vShape = new ArrayList();
    
    private boolean editar;
    Shape seleccionado;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        editar = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cb_editar = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        cb_editar.setText("Editar");
        cb_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_editarActionPerformed(evt);
            }
        });
        jPanel1.add(cb_editar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_editarActionPerformed
        editar = cb_editar.isSelected();
    }//GEN-LAST:event_cb_editarActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        if(!editar){
            rectangulo.setFrameFromDiagonal(paux, evt.getPoint());
        }else{
            if(seleccionado!=null){
                Rectangle r = (Rectangle)seleccionado;
                r.setLocation(evt.getPoint());
            }
        }
        this.repaint();
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        if (!editar){
            paux = evt.getPoint();
            rectangulo = new Rectangle(paux);
            vShape.add(rectangulo);
        }else{
            seleccionado = getSelectedShape(evt.getPoint());
        }
    }//GEN-LAST:event_formMousePressed

    private Shape getSelectedShape(Point2D p){
        for(Shape s:vShape)
            if(s.contains(p)) return s;
        return null;
    }
    
    public void paint(Graphics g){
        super.paint(g);
        Graphics2D g2d = (Graphics2D) g;
        this.setAtributos(g2d);
        for (Shape s: vShape)
            g2d.draw(s);
        
        /*if (linea != null)
            g2d.draw(linea);
        
        if (rectangulo != null)
            g2d.draw(rectangulo);*/
        /*Point2D p1 = new Point2D.Float(100,100);
        Point2D p2 = new Point2D.Float(200,200);
        Line2D linea = new Line2D.Float(p1,p2);
        Point2D pc1 = new Point2D.Float(200,100);
        Point2D pc2 = new Point2D.Float(100,200);
        QuadCurve2D q = new QuadCurve2D.Float();
        q.setCurve(p1,pc1,p2);
        CubicCurve2D c = new CubicCurve2D.Float();
        c.setCurve(p1, pc1, pc2, p2);
        Rectangle2D r = new Rectangle2D.Double(p1.getX(),p1.getY(),100,100);
        RoundRectangle2D rr = new RoundRectangle2D.Double(p1.getX(),p1.getY(),100,100,50,50);
        Ellipse2D e = new Ellipse2D.Double(p1.getX(),p1.getY(),100,100);
        
        g2d.draw(e);
        g2d.draw(rr);
        g2d.draw(r);
        g2d.draw(c);
        g2d.draw(q);
        g2d.draw(linea);*/
        
    }
    
    private void setAtributos(Graphics2D g2d){
        Stroke trazo;
        float patronDiscontinuidad[] = {15.0f, 15.0f};
        trazo = new BasicStroke(10.0f, BasicStroke.CAP_ROUND, BasicStroke.JOIN_MITER,1.0f,patronDiscontinuidad, 0.0f);
        g2d.setStroke(trazo);
        
        Paint relleno;
        relleno = new Color(255,100,0);
        g2d.setPaint(relleno);
        g2d.draw(new Rectangle(170,40,120,120));
        g2d.fill(new Rectangle(300,40,120,120));
        
        Point pc1 = new Point(430,40), pc2 = new Point(550,160);
        relleno = new GradientPaint(pc1,Color.RED, pc2, Color.BLUE);
        g2d.setPaint(relleno);
        g2d.fill(new Rectangle(460,40,120,120));
        
        Composite comp;
        comp = AlphaComposite.getInstance(AlphaComposite.SRC_OVER,0.5f);
        g2d.setComposite(comp);
        g2d.fill(new Rectangle(190,100,200,120));
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb_editar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
