package practica7;

import SM.MRC.util.Colores;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.Point2D;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JToggleButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Mario
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        miInitComponents();
    }

    public JLabel getBarraEstado() {
        return barraEstado;
    }

    public JCheckBox getCbAlisar() {
        return cbAlisar;
    }

    public JCheckBox getCbEditar() {
        return cbEditar;
    }

    public JCheckBox getCbRelleno() {
        return cbRelleno;
    }

    public JCheckBox getCbTransparencia() {
        return cbTransparencia;
    }

    public ButtonGroup getGrupoBarraHerramientas() {
        return grupoBarraHerramientas;
    }

    public JCheckBoxMenuItem getItemAtributos() {
        return itemAtributos;
    }

    public JSpinner getSpinnerGrosor() {
        return spinnerGrosor;
    }
        
    private void miInitComponents(){
        
        class ColorListener extends MouseAdapter  {
            ColorListener() {}
            public void mouseClicked(MouseEvent evt) {
                JButton botonColor = (JButton) evt.getSource();
                getVentanaInternaActiva().getLienzo2D().setColor(Colores.valueOf(botonColor.getName()));
                getVentanaInternaActiva().getLienzo2D().repaint();
            }
        }
        ColorListener colorListener = new ColorListener();
        botonNegro.addMouseListener(colorListener);
        botonRojo.addMouseListener(colorListener);
        botonAzul.addMouseListener(colorListener);
        botonBlanco.addMouseListener(colorListener);
        botonAmarillo.addMouseListener(colorListener);
        botonVerde.addMouseListener(colorListener);
        
        class HerramientasListener extends MouseAdapter {
            HerramientasListener(){}
            public void mouseClicked(MouseEvent evt){
                JToggleButton herramientaBoton = (JToggleButton) evt.getSource();
                getVentanaInternaActiva().getLienzo2D().setHerramienta(herramientaBoton.getName());
                barraEstado.setText(herramientaBoton.getName());
            }
        }
        HerramientasListener herramientasListener = new HerramientasListener();
        botonLapiz.addMouseListener(herramientasListener);
        botonLinea.addMouseListener(herramientasListener);
        botonRectangulo.addMouseListener(herramientasListener);
        botonElipse.addMouseListener(herramientasListener);
        
    }
    
    public VentanaInterna getVentanaInternaActiva(){
        return (VentanaInterna)escritorio.getSelectedFrame();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBarraHerramientas = new javax.swing.ButtonGroup();
        grupoColores = new javax.swing.ButtonGroup();
        dialogoAbrir = new javax.swing.JDialog();
        fileChooserAbrir = new javax.swing.JFileChooser();
        dialogoGuardar = new javax.swing.JDialog();
        fileChooserGuardar = new javax.swing.JFileChooser();
        barraFormas = new javax.swing.JToolBar();
        botonLapiz = new javax.swing.JToggleButton();
        botonLinea = new javax.swing.JToggleButton();
        botonRectangulo = new javax.swing.JToggleButton();
        botonElipse = new javax.swing.JToggleButton();
        panelPrincipal = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        barraAtributos = new javax.swing.JToolBar();
        panelColor = new javax.swing.JPanel();
        panelLabelColor = new javax.swing.JPanel();
        labelColor = new javax.swing.JLabel();
        panelBotonesColor = new javax.swing.JPanel();
        botonNegro = new javax.swing.JButton();
        botonRojo = new javax.swing.JButton();
        botonAzul = new javax.swing.JButton();
        botonBlanco = new javax.swing.JButton();
        botonAmarillo = new javax.swing.JButton();
        botonVerde = new javax.swing.JButton();
        panelGrosor = new javax.swing.JPanel();
        panelLabelGrosor = new javax.swing.JPanel();
        labelGrosor = new javax.swing.JLabel();
        panelComboGrosor = new javax.swing.JPanel();
        spinnerGrosor = new javax.swing.JSpinner();
        panelAtributos = new javax.swing.JPanel();
        panelVacioAtributos = new javax.swing.JPanel();
        panelCBAtributos = new javax.swing.JPanel();
        cbRelleno = new javax.swing.JCheckBox();
        cbTransparencia = new javax.swing.JCheckBox();
        cbAlisar = new javax.swing.JCheckBox();
        cbEditar = new javax.swing.JCheckBox();
        barraEstado = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemNuevo = new javax.swing.JMenuItem();
        itemAbrir = new javax.swing.JMenuItem();
        itemGuardar = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        itemEstado = new javax.swing.JCheckBoxMenuItem();
        itemFormas = new javax.swing.JCheckBoxMenuItem();
        itemAtributos = new javax.swing.JCheckBoxMenuItem();

        FormListener formListener = new FormListener();

        dialogoAbrir.setSize(new java.awt.Dimension(643, 419));
        dialogoAbrir.getContentPane().setLayout(new javax.swing.BoxLayout(dialogoAbrir.getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        dialogoAbrir.getContentPane().add(fileChooserAbrir);

        dialogoGuardar.setSize(new java.awt.Dimension(643, 419));
        dialogoGuardar.getContentPane().setLayout(new javax.swing.BoxLayout(dialogoGuardar.getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        dialogoGuardar.getContentPane().add(fileChooserGuardar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PaintBásico2D MRC");
        setPreferredSize(new java.awt.Dimension(845, 600));
        addWindowListener(formListener);

        barraFormas.setRollover(true);
        barraFormas.setPreferredSize(new java.awt.Dimension(100, 31));
        barraFormas.addPropertyChangeListener(formListener);

        grupoBarraHerramientas.add(botonLapiz);
        botonLapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Lapiz.gif"))); // NOI18N
        botonLapiz.setSelected(true);
        botonLapiz.setFocusable(false);
        botonLapiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonLapiz.setName("Punto"); // NOI18N
        botonLapiz.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraFormas.add(botonLapiz);

        grupoBarraHerramientas.add(botonLinea);
        botonLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Linea.gif"))); // NOI18N
        botonLinea.setFocusable(false);
        botonLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonLinea.setName("Línea"); // NOI18N
        botonLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraFormas.add(botonLinea);

        grupoBarraHerramientas.add(botonRectangulo);
        botonRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Rectangulo.gif"))); // NOI18N
        botonRectangulo.setFocusable(false);
        botonRectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRectangulo.setName("Rectángulo"); // NOI18N
        botonRectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraFormas.add(botonRectangulo);

        grupoBarraHerramientas.add(botonElipse);
        botonElipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Ovalo.gif"))); // NOI18N
        botonElipse.setFocusable(false);
        botonElipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonElipse.setName("Elipse"); // NOI18N
        botonElipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraFormas.add(botonElipse);

        getContentPane().add(barraFormas, java.awt.BorderLayout.NORTH);

        panelPrincipal.setPreferredSize(new java.awt.Dimension(741, 100));
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        escritorio.setPreferredSize(new java.awt.Dimension(845, 200));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 841, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        panelPrincipal.add(escritorio, java.awt.BorderLayout.CENTER);

        barraAtributos.setRollover(true);
        barraAtributos.setMinimumSize(new java.awt.Dimension(100, 100));
        barraAtributos.setPreferredSize(new java.awt.Dimension(530, 100));
        barraAtributos.addPropertyChangeListener(formListener);

        panelColor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 5));
        panelColor.setPreferredSize(new java.awt.Dimension(120, 98));
        panelColor.setLayout(new java.awt.BorderLayout());

        panelLabelColor.setPreferredSize(new java.awt.Dimension(130, 18));

        labelColor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelColor.setText("Color");
        labelColor.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelColor.setPreferredSize(new java.awt.Dimension(29, 25));
        labelColor.setRequestFocusEnabled(false);

        javax.swing.GroupLayout panelLabelColorLayout = new javax.swing.GroupLayout(panelLabelColor);
        panelLabelColor.setLayout(panelLabelColorLayout);
        panelLabelColorLayout.setHorizontalGroup(
            panelLabelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelColor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelLabelColorLayout.setVerticalGroup(
            panelLabelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLabelColorLayout.createSequentialGroup()
                .addComponent(labelColor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelColor.add(panelLabelColor, java.awt.BorderLayout.NORTH);

        panelBotonesColor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        panelBotonesColor.setAlignmentY(2.0F);
        panelBotonesColor.setPreferredSize(new java.awt.Dimension(120, 80));

        botonNegro.setBackground(new java.awt.Color(0, 0, 0));
        grupoColores.add(botonNegro);
        botonNegro.setFocusable(false);
        botonNegro.setName("Negro"); // NOI18N

        botonRojo.setBackground(new java.awt.Color(255, 0, 0));
        grupoColores.add(botonRojo);
        botonRojo.setFocusable(false);
        botonRojo.setName("Rojo"); // NOI18N

        botonAzul.setBackground(new java.awt.Color(0, 0, 255));
        botonAzul.setAlignmentX(0.5F);
        grupoColores.add(botonAzul);
        botonAzul.setFocusable(false);
        botonAzul.setName("Azul"); // NOI18N

        botonBlanco.setBackground(new java.awt.Color(255, 255, 255));
        grupoColores.add(botonBlanco);
        botonBlanco.setFocusable(false);
        botonBlanco.setName("Blanco"); // NOI18N

        botonAmarillo.setBackground(new java.awt.Color(255, 255, 0));
        grupoColores.add(botonAmarillo);
        botonAmarillo.setFocusable(false);
        botonAmarillo.setName("Amarillo"); // NOI18N

        botonVerde.setBackground(new java.awt.Color(0, 255, 0));
        botonVerde.setAlignmentY(0.0F);
        grupoColores.add(botonVerde);
        botonVerde.setFocusable(false);
        botonVerde.setName("Verde"); // NOI18N

        javax.swing.GroupLayout panelBotonesColorLayout = new javax.swing.GroupLayout(panelBotonesColor);
        panelBotonesColor.setLayout(panelBotonesColorLayout);
        panelBotonesColorLayout.setHorizontalGroup(
            panelBotonesColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesColorLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelBotonesColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotonesColorLayout.createSequentialGroup()
                        .addComponent(botonBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBotonesColorLayout.createSequentialGroup()
                        .addComponent(botonNegro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );
        panelBotonesColorLayout.setVerticalGroup(
            panelBotonesColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesColorLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelBotonesColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNegro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBotonesColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        panelColor.add(panelBotonesColor, java.awt.BorderLayout.CENTER);

        barraAtributos.add(panelColor);

        panelGrosor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 5));
        panelGrosor.setPreferredSize(new java.awt.Dimension(120, 98));
        panelGrosor.setLayout(new java.awt.BorderLayout());

        panelLabelGrosor.setPreferredSize(new java.awt.Dimension(120, 18));
        panelLabelGrosor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelGrosor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelGrosor.setText("Grosor");
        labelGrosor.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelGrosor.setPreferredSize(new java.awt.Dimension(38, 25));
        panelLabelGrosor.add(labelGrosor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 20));

        panelGrosor.add(panelLabelGrosor, java.awt.BorderLayout.NORTH);

        panelComboGrosor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        panelComboGrosor.setAlignmentY(2.0F);
        panelComboGrosor.setPreferredSize(new java.awt.Dimension(120, 50));

        spinnerGrosor.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spinnerGrosor.setMinimumSize(new java.awt.Dimension(40, 20));
        spinnerGrosor.setPreferredSize(new java.awt.Dimension(50, 30));
        spinnerGrosor.addChangeListener(formListener);
        panelComboGrosor.add(spinnerGrosor);

        panelGrosor.add(panelComboGrosor, java.awt.BorderLayout.CENTER);

        barraAtributos.add(panelGrosor);

        panelAtributos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        panelAtributos.setPreferredSize(new java.awt.Dimension(250, 98));
        panelAtributos.setLayout(new java.awt.BorderLayout());

        panelVacioAtributos.setPreferredSize(new java.awt.Dimension(250, 18));

        javax.swing.GroupLayout panelVacioAtributosLayout = new javax.swing.GroupLayout(panelVacioAtributos);
        panelVacioAtributos.setLayout(panelVacioAtributosLayout);
        panelVacioAtributosLayout.setHorizontalGroup(
            panelVacioAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        panelVacioAtributosLayout.setVerticalGroup(
            panelVacioAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        panelAtributos.add(panelVacioAtributos, java.awt.BorderLayout.NORTH);

        panelCBAtributos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        panelCBAtributos.setAlignmentY(0.0F);
        panelCBAtributos.setPreferredSize(new java.awt.Dimension(250, 80));
        panelCBAtributos.setLayout(new java.awt.GridLayout(2, 2));

        cbRelleno.setText("Relleno");
        cbRelleno.setActionCommand("");
        cbRelleno.setAlignmentY(0.0F);
        cbRelleno.setPreferredSize(new java.awt.Dimension(61, 10));
        cbRelleno.addActionListener(formListener);
        panelCBAtributos.add(cbRelleno);

        cbTransparencia.setText("Transparencia");
        cbTransparencia.setActionCommand("");
        cbTransparencia.setAlignmentY(0.0F);
        cbTransparencia.setPreferredSize(new java.awt.Dimension(93, 10));
        cbTransparencia.addActionListener(formListener);
        panelCBAtributos.add(cbTransparencia);

        cbAlisar.setText("Alisar");
        cbAlisar.setActionCommand("");
        cbAlisar.setAlignmentY(0.0F);
        cbAlisar.setPreferredSize(new java.awt.Dimension(51, 10));
        cbAlisar.addActionListener(formListener);
        panelCBAtributos.add(cbAlisar);

        cbEditar.setText("Editar");
        cbEditar.setActionCommand("");
        cbEditar.setAlignmentY(0.0F);
        cbEditar.setPreferredSize(new java.awt.Dimension(53, 10));
        cbEditar.addActionListener(formListener);
        panelCBAtributos.add(cbEditar);

        panelAtributos.add(panelCBAtributos, java.awt.BorderLayout.CENTER);

        barraAtributos.add(panelAtributos);

        panelPrincipal.add(barraAtributos, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        barraEstado.setText("Punto");
        barraEstado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(barraEstado, java.awt.BorderLayout.SOUTH);

        menuArchivo.setText("Archivo");

        itemNuevo.setText("Nuevo");
        itemNuevo.addActionListener(formListener);
        menuArchivo.add(itemNuevo);

        itemAbrir.setText("Abrir");
        itemAbrir.addActionListener(formListener);
        menuArchivo.add(itemAbrir);

        itemGuardar.setText("Guardar");
        itemGuardar.addActionListener(formListener);
        menuArchivo.add(itemGuardar);

        menuPrincipal.add(menuArchivo);

        menuEditar.setText("Edicion");

        itemEstado.setSelected(true);
        itemEstado.setText("Ver barra de estado");
        itemEstado.addActionListener(formListener);
        menuEditar.add(itemEstado);

        itemFormas.setSelected(true);
        itemFormas.setText("Ver barra de formas");
        itemFormas.addActionListener(formListener);
        menuEditar.add(itemFormas);

        itemAtributos.setSelected(true);
        itemAtributos.setText("Ver barra de atributos");
        itemAtributos.addActionListener(formListener);
        menuEditar.add(itemAtributos);

        menuPrincipal.add(menuEditar);

        setJMenuBar(menuPrincipal);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.WindowListener, java.beans.PropertyChangeListener, javax.swing.event.ChangeListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == cbRelleno) {
                VentanaPrincipal.this.cbRellenoActionPerformed(evt);
            }
            else if (evt.getSource() == cbTransparencia) {
                VentanaPrincipal.this.cbTransparenciaActionPerformed(evt);
            }
            else if (evt.getSource() == cbAlisar) {
                VentanaPrincipal.this.cbAlisarActionPerformed(evt);
            }
            else if (evt.getSource() == cbEditar) {
                VentanaPrincipal.this.cbEditarActionPerformed(evt);
            }
            else if (evt.getSource() == itemNuevo) {
                VentanaPrincipal.this.itemNuevoActionPerformed(evt);
            }
            else if (evt.getSource() == itemAbrir) {
                VentanaPrincipal.this.itemAbrirActionPerformed(evt);
            }
            else if (evt.getSource() == itemGuardar) {
                VentanaPrincipal.this.itemGuardarActionPerformed(evt);
            }
            else if (evt.getSource() == itemEstado) {
                VentanaPrincipal.this.itemEstadoActionPerformed(evt);
            }
            else if (evt.getSource() == itemFormas) {
                VentanaPrincipal.this.itemFormasActionPerformed(evt);
            }
            else if (evt.getSource() == itemAtributos) {
                VentanaPrincipal.this.itemAtributosActionPerformed(evt);
            }
        }

        public void windowActivated(java.awt.event.WindowEvent evt) {
        }

        public void windowClosed(java.awt.event.WindowEvent evt) {
        }

        public void windowClosing(java.awt.event.WindowEvent evt) {
        }

        public void windowDeactivated(java.awt.event.WindowEvent evt) {
        }

        public void windowDeiconified(java.awt.event.WindowEvent evt) {
        }

        public void windowIconified(java.awt.event.WindowEvent evt) {
        }

        public void windowOpened(java.awt.event.WindowEvent evt) {
            if (evt.getSource() == VentanaPrincipal.this) {
                VentanaPrincipal.this.formWindowOpened(evt);
            }
        }

        public void propertyChange(java.beans.PropertyChangeEvent evt) {
            if (evt.getSource() == barraFormas) {
                VentanaPrincipal.this.barraFormasPropertyChange(evt);
            }
            else if (evt.getSource() == barraAtributos) {
                VentanaPrincipal.this.barraAtributosPropertyChange(evt);
            }
        }

        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            if (evt.getSource() == spinnerGrosor) {
                VentanaPrincipal.this.spinnerGrosorStateChanged(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void itemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNuevoActionPerformed
        VentanaInterna vi = new VentanaInterna(this);
        // Mostrar las nuevas ventanas en cascada
        if(escritorio.getComponentCount()>0){
            // Obtener la posición de la última ventana
            Point2D p_ultima_vi = escritorio.getComponents()[0].getLocation();
            Point2D cascada = new Point((int)p_ultima_vi.getX()+25, (int)p_ultima_vi.getY()+25);
            vi.setLocation((Point) cascada);
        }
        escritorio.add(vi);
        vi.setVisible(true);
        
    }//GEN-LAST:event_itemNuevoActionPerformed

    private void itemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAbrirActionPerformed
        dialogoAbrir.setVisible(true); 
        dialogoAbrir.setTitle("Abrir");
        double x = this.getWidth()/2 - dialogoAbrir.getWidth()/2;
        double y = this.getHeight()/2 - dialogoAbrir.getHeight()/2;
        dialogoAbrir.setLocation(new Point((int)x,(int)y));
    }//GEN-LAST:event_itemAbrirActionPerformed

    private void itemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGuardarActionPerformed
        dialogoGuardar.setVisible(true); 
        dialogoGuardar.setTitle("Guardar");
        double x = this.getWidth()/2 - dialogoGuardar.getWidth()/2;
        double y = this.getHeight()/2 - dialogoGuardar.getHeight()/2;
        dialogoGuardar.setLocation(new Point((int)x,(int)y));
    }//GEN-LAST:event_itemGuardarActionPerformed

    private void itemEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEstadoActionPerformed
        barraEstado.setVisible(itemEstado.isSelected());
    }//GEN-LAST:event_itemEstadoActionPerformed

    private void itemFormasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFormasActionPerformed
        barraFormas.setVisible(itemFormas.isSelected());
    }//GEN-LAST:event_itemFormasActionPerformed

    private void itemAtributosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAtributosActionPerformed
        barraAtributos.setVisible(itemAtributos.isSelected());
    }//GEN-LAST:event_itemAtributosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        VentanaInterna vi = new VentanaInterna(this);
        escritorio.add(vi);
        vi.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void barraAtributosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_barraAtributosPropertyChange
        if(evt.getPropertyName() == "orientation"){
            if(barraAtributos.getOrientation() == 0)
                barraAtributos.setPreferredSize(new Dimension(530,100));
            if(barraAtributos.getOrientation() == 1)
                barraAtributos.setPreferredSize(new Dimension(260,330));        
        }
    }//GEN-LAST:event_barraAtributosPropertyChange

    private void cbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEditarActionPerformed
        getVentanaInternaActiva().getLienzo2D().setEditar(cbEditar.isSelected());
    }//GEN-LAST:event_cbEditarActionPerformed

    private void cbAlisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlisarActionPerformed
        getVentanaInternaActiva().getLienzo2D().setAlisar(cbAlisar.isSelected());
        getVentanaInternaActiva().getLienzo2D().repaint();
    }//GEN-LAST:event_cbAlisarActionPerformed

    private void cbTransparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTransparenciaActionPerformed
        getVentanaInternaActiva().getLienzo2D().setTransparencia(cbTransparencia.isSelected());
        getVentanaInternaActiva().getLienzo2D().repaint();
    }//GEN-LAST:event_cbTransparenciaActionPerformed

    private void cbRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRellenoActionPerformed
        getVentanaInternaActiva().getLienzo2D().setRelleno(cbRelleno.isSelected());
        getVentanaInternaActiva().getLienzo2D().repaint();
    }//GEN-LAST:event_cbRellenoActionPerformed

    private void spinnerGrosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerGrosorStateChanged
        getVentanaInternaActiva().getLienzo2D().setGrosor((int) spinnerGrosor.getValue());
        getVentanaInternaActiva().getLienzo2D().repaint();
    }//GEN-LAST:event_spinnerGrosorStateChanged

    private void barraFormasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_barraFormasPropertyChange
        if(evt.getPropertyName() == "orientation"){
            if(barraFormas.getOrientation() == 0)
                barraFormas.setPreferredSize(new Dimension(130,35));
            if(barraFormas.getOrientation() == 1)
                barraFormas.setPreferredSize(new Dimension(35,130));   
        }
    }//GEN-LAST:event_barraFormasPropertyChange

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraAtributos;
    private javax.swing.JLabel barraEstado;
    private javax.swing.JToolBar barraFormas;
    private javax.swing.JButton botonAmarillo;
    private javax.swing.JButton botonAzul;
    private javax.swing.JButton botonBlanco;
    private javax.swing.JToggleButton botonElipse;
    private javax.swing.JToggleButton botonLapiz;
    private javax.swing.JToggleButton botonLinea;
    private javax.swing.JButton botonNegro;
    private javax.swing.JToggleButton botonRectangulo;
    private javax.swing.JButton botonRojo;
    private javax.swing.JButton botonVerde;
    private javax.swing.JCheckBox cbAlisar;
    private javax.swing.JCheckBox cbEditar;
    private javax.swing.JCheckBox cbRelleno;
    private javax.swing.JCheckBox cbTransparencia;
    private javax.swing.JDialog dialogoAbrir;
    private javax.swing.JDialog dialogoGuardar;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JFileChooser fileChooserAbrir;
    private javax.swing.JFileChooser fileChooserGuardar;
    private javax.swing.ButtonGroup grupoBarraHerramientas;
    private javax.swing.ButtonGroup grupoColores;
    private javax.swing.JMenuItem itemAbrir;
    private javax.swing.JCheckBoxMenuItem itemAtributos;
    private javax.swing.JCheckBoxMenuItem itemEstado;
    private javax.swing.JCheckBoxMenuItem itemFormas;
    private javax.swing.JMenuItem itemGuardar;
    private javax.swing.JMenuItem itemNuevo;
    private javax.swing.JLabel labelColor;
    private javax.swing.JLabel labelGrosor;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JPanel panelAtributos;
    private javax.swing.JPanel panelBotonesColor;
    private javax.swing.JPanel panelCBAtributos;
    private javax.swing.JPanel panelColor;
    private javax.swing.JPanel panelComboGrosor;
    private javax.swing.JPanel panelGrosor;
    private javax.swing.JPanel panelLabelColor;
    private javax.swing.JPanel panelLabelGrosor;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelVacioAtributos;
    private javax.swing.JSpinner spinnerGrosor;
    // End of variables declaration//GEN-END:variables
}
