/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7plus;

import SM.MRC.iu.Lienzo2D;
import java.awt.Color;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JButton;
import javax.swing.JToggleButton;

/**
 *
 * @author Mario
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    private VentanaPrincipal parent = null;

    public Lienzo2D getLienzo2D() {
        return lienzo2D;
    }    
    
    /**
     * Creates new form VentanaInterna
     */
    public VentanaInterna(VentanaPrincipal parent) {
        initComponents();
        this.parent = parent;
        //lienzo2D.setLabelPosicion(parent.getLabelPosicion());
        //lienzo2D.setPanelPosicion(parent.getPanelPosicion());
        lienzo2D.setBorde(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanel = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        lienzo2D = new SM.MRC.iu.Lienzo2D();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nuevo lienzo");
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(300, 350));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(false);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panel.setBackground(new java.awt.Color(204, 204, 204));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout lienzo2DLayout = new javax.swing.GroupLayout(lienzo2D);
        lienzo2D.setLayout(lienzo2DLayout);
        lienzo2DLayout.setHorizontalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        lienzo2DLayout.setVerticalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        panel.add(lienzo2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 300));

        scrollPanel.setViewportView(panel);

        getContentPane().add(scrollPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated

        parent.getGrupoBarraHerramientas().clearSelection();

        // Obtener el JToggleButton seleccionado del grupo de botones
        JToggleButton jb = new JToggleButton(); int i = 0;
        for (Enumeration<AbstractButton> h = parent.getGrupoBarraHerramientas().getElements(); h.hasMoreElements();) {
            jb = (JToggleButton) h.nextElement();
            if(i==lienzo2D.getHerramienta().ordinal())
                break;
            i++;
        }
        jb.setSelected(true);

        parent.getBarraEstado().setText(jb.getName());
        
        JButton cb = new JButton(); i = 0;
        for (Enumeration<AbstractButton> h = parent.getGrupoColores().getElements(); h.hasMoreElements();) {
            cb = (JButton) h.nextElement();
            if(i==lienzo2D.getColor().ordinal())
                break;
            i++;
        }
        
        parent.getComboColor().setSelectedIndex(i);
        
        parent.getSpinnerGrosor().setValue(lienzo2D.getGrosor());

        parent.getBotonRelleno().setSelected(lienzo2D.isRelleno());
        parent.getBotonTransparencia().setSelected(lienzo2D.isTransparencia());
        parent.getBotonAlisar().setSelected(lienzo2D.isAlisar());
        
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SM.MRC.iu.Lienzo2D lienzo2D;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables
}
