/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica14;

import SM.MRC.util.Util;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import java.awt.BorderLayout;
import java.awt.image.BufferedImage;

/**
 *
 * @author Mario
 */
public class VentanaInternaCamara extends javax.swing.JInternalFrame {

    private Webcam camara = null;
    VentanaPrincipal parent =null;
    /**
     * Creates new form VentanaInternaCamara
     */
    private VentanaInternaCamara(VentanaPrincipal parent) {
        initComponents();
        camara = Webcam.getDefault();
        if (camara != null) {
            WebcamPanel areaVisual = new WebcamPanel(camara);
            if (areaVisual != null) {
                getContentPane().add(areaVisual, BorderLayout.CENTER);
                pack();
            }
        }
        this.parent = parent;
    }
    
    public static VentanaInternaCamara getInstance(VentanaPrincipal parent) {
        VentanaInternaCamara v = new VentanaInternaCamara(parent);
        return (v.camara != null ? v : null);
    }

    public void captruarPantalla(){
        VentanaInterna vi = null;
        if(camara!=null){
            vi = new VentanaInterna(parent);
            vi.mostrarVentanaCascada(parent.getEscritorio());
            vi.setVisible(true);
            vi.getLienzo().setImagen(camara.getImage());
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
